name: Bug Report
description: Report something that isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to help us investigate.

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I'm using the latest version of capscr
          required: true
        - label: I searched existing issues and this hasn't been reported
          required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: When I try to capture a region, the selection overlay...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we recreate this issue?
      placeholder: |
        1. Open capscr
        2. Press Ctrl+Shift+R
        3. Select a region
        4. ...
    validations:
      required: true

  - type: dropdown
    id: capture-mode
    attributes:
      label: Capture Mode
      description: Which capture mode were you using?
      options:
        - Full Screen
        - Window
        - Region
        - GIF Recording
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows 10
        - Windows 11
        - Linux (X11)
        - Linux (Wayland)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: capscr Version
      description: Run capscr --version or check the release you downloaded
      placeholder: "0.2.0"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, error messages, logs, or anything else helpful
    validations:
      required: false
